# Generated by Django 3.1.1 on 2021-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(default='random', max_length=300)),
                ('Description', models.CharField(default='random', max_length=500)),
                ('Location', models.CharField(default='random', max_length=200)),
                ('RegFrom', models.DateTimeField()),
                ('RegTo', models.DateTimeField()),
                ('Deadline', models.DateTimeField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(default='random', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParticipantName', models.CharField(default='random', max_length=300)),
                ('ContactNumber', models.IntegerField(default='0000000000')),
                ('Email', models.EmailField(max_length=254)),
                ('Event', models.CharField(default='SampleEvent', max_length=100)),
                ('RegistrationType', models.CharField(default='NA', max_length=50)),
                ('NumOfPeople', models.IntegerField(default='1')),
            ],
        ),
    ]
