# Generated by Django 3.1.4 on 2021-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=300, unique=True)),
                ('Description', models.CharField(max_length=500)),
                ('Location', models.CharField(choices=[('Online', 'On'), ('Offline', 'Of')], default='Online', max_length=7)),
                ('RegFrom', models.TimeField()),
                ('RegTo', models.TimeField()),
                ('Deadline', models.TimeField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
