# Generated by Django 3.1.4 on 2021-01-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210119_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantreg',
            name='EventNumber',
            field=models.IntegerField(default=True, max_length=4),
        ),
    ]
