# Generated by Django 3.1.4 on 2021-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_participantreg_eventnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantreg',
            name='EventNumber',
            field=models.IntegerField(default=True),
        ),
    ]
