# Generated by Django 3.1.4 on 2021-01-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210119_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantreg',
            name='EventNumber',
        ),
    ]
